<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="8.1.2" />
    <PackageVersion Include="InfluxDB3.Client" Version="1.4.0-dev.1720" />
    <PackageVersion Include="net-questdb-client" Version="3.0.0" />
    <PackageVersion Include="MongoDB.Driver" Version="3.4.0" />
  </ItemGroup>
</Project>