namespace Aviator.Main.Decoders;

/// <summary>Human-readable meanings for common ACARS message labels (ARINC 620 / 618).</summary>
public static class AcarsLabels
{
    public static string? Describe(string? label) =>
        label is null ? null : Catalog.GetValueOrDefault(label);

    private static readonly Dictionary<string, string> Catalog = new(StringComparer.Ordinal)
    {
        ["_d"] = "No message (polled mode)",
        ["00"] = "Emergency situation report",
        ["10"] = "Aircraft report",
        ["15"] = "Position report",
        ["16"] = "Position report (navigation)",
        ["17"] = "ETA report",
        ["20"] = "Aircraft addressed downlink",
        ["2S"] = "Weather request",
        ["2U"] = "Weather report",
        ["30"] = "Aircraft addressed downlink",
        ["32"] = "Aircraft addressed downlink",
        ["33"] = "Aircraft addressed downlink",
        ["4A"] = "Latest ADS report",
        ["4M"] = "Cargo information",
        ["51"] = "Ground GMT request/response",
        ["52"] = "Ground UTC request/response",
        ["54"] = "Voice-to-ACARS change advisory",
        ["57"] = "Alternate aircrew-initiated position report",
        ["5D"] = "ATIS request",
        ["5U"] = "Weather request",
        ["5Y"] = "Revision to previous ETA",
        ["5Z"] = "Airline designated downlink",
        ["7A"] = "Aircraft-initiated engine data",
        ["7B"] = "Aircraft-initiated miscellaneous message",
        ["80"] = "Aircraft addressed downlink",
        ["83"] = "Aircraft addressed downlink",
        ["A1"] = "Deliver oceanic clearance",
        ["A2"] = "Deliver departure clearance",
        ["A4"] = "Acknowledge PDC",
        ["A5"] = "Request position report",
        ["A6"] = "Request ADS report",
        ["A7"] = "Forward free text to aircraft",
        ["A8"] = "Deliver departure slot",
        ["A9"] = "Deliver ATIS information",
        ["A0"] = "ATIS facilities notification",
        ["AA"] = "ATC communications",
        ["AB"] = "Terminal weather information for pilots",
        ["B1"] = "Request oceanic clearance",
        ["B2"] = "Request oceanic readback",
        ["B3"] = "Request departure clearance",
        ["B4"] = "Acknowledge departure clearance",
        ["B5"] = "Provide position report",
        ["B6"] = "Provide ADS report",
        ["B7"] = "Forward free text to ATS",
        ["B8"] = "Request departure slot",
        ["B9"] = "Request ATIS information",
        ["B0"] = "ATS facility notification",
        ["BA"] = "ATC communications",
        ["C0"] = "Uplink message to all cockpit printers",
        ["C1"] = "Uplink message to printer #1",
        ["CA"] = "Printer status: error",
        ["CB"] = "Printer status: busy",
        ["CC"] = "Printer status: local",
        ["CD"] = "Printer status: no paper",
        ["CE"] = "Printer status: buffer overrun",
        ["CF"] = "Printer status: reserved",
        ["F3"] = "Dedicated transceiver advisory",
        ["H1"] = "Message to/from terminal (FMC, DFDAU…)",
        ["H2"] = "Meteorological report",
        ["H3"] = "Icing report",
        ["HX"] = "Undelivered uplink report",
        ["M1"] = "IATA departure message",
        ["M2"] = "IATA arrival message",
        ["M3"] = "IATA return to ramp",
        ["M4"] = "IATA return from airborne",
        ["Q0"] = "Link test",
        ["Q1"] = "ETA (departure/arrival stations)",
        ["Q2"] = "ETA",
        ["Q3"] = "Clock update",
        ["Q4"] = "Voice circuit busy",
        ["Q5"] = "Unable to process uplink",
        ["Q6"] = "Voice-to-ACARS change",
        ["Q7"] = "Delay message",
        ["QA"] = "OUT report (fuel)",
        ["QB"] = "OFF report",
        ["QC"] = "ON report",
        ["QD"] = "IN report (fuel)",
        ["QE"] = "OUT report (fuel, destination)",
        ["QF"] = "OFF report (destination)",
        ["QG"] = "OUT report (return to gate)",
        ["QH"] = "OUT report",
        ["QK"] = "Landing report",
        ["QL"] = "Arrival report",
        ["QM"] = "Arrival information",
        ["QN"] = "Diversion report",
        ["QP"] = "OUT report",
        ["QQ"] = "OFF report",
        ["QR"] = "ON report",
        ["QS"] = "IN report",
        ["QT"] = "OUT/return IN report",
        ["RA"] = "Command aircraft to transmit data",
        ["RB"] = "Response to RA command",
        ["S1"] = "Network statistics request",
        ["S2"] = "System status request",
        ["SA"] = "Media advisory",
        ["SQ"] = "Squitter (ground station ident)",
    };
}
